### ISSUE TITLE
Panicking when clicking on new file

### ISSUE THREAD

**Issue by bjorn3** [Logicalshift/flowbetween#4]
```
     Running `target/release/flow_between`
 INFO  flo_ui_files::sqlite::file_manager > Using data directory at `/home/bjorn/.local/share/app.flowbetween/default/data`
 INFO  flo_ui_files::sqlite::file_list    > File list database version 2 INFO  flo_ui_files::sqlite::file_manager > Created new file at `/home/bjorn/.local/share/app.flowbetween/default/data/cc3cea8bc59c437ba2dececde619f008`

(flow_between:9135): Gtk-CRITICAL **: 22:02:55.072: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(flow_between:9135): GdkPixbuf-CRITICAL **: 22:02:55.077: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed

(flow_between:9135): GdkPixbuf-CRITICAL **: 22:02:55.078: gdk_pixbuf_scale_simple: assertion 'dest_width > 0' failed

(flow_between:9135): Gtk-WARNING **: 22:02:55.081: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkButton)

(flow_between:9135): Gtk-WARNING **: 22:02:55.081: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node button, owner GtkButton)

(flow_between:9135): Gtk-CRITICAL **: 22:02:55.083: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

(flow_between:9135): Gtk-CRITICAL **: 22:02:55.083: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
thread '<unnamed>' panicked at 'Enabling options: Unexpected OpenGL errors: [UnknownError(1282)]', render/src/gl_renderer/error.rs:19:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1076
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1537
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:486
  11: rust_begin_unwind
             at src/libstd/panicking.rs:388
  12: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:342
  13: flo_render::gl_renderer::error::panic_on_gl_error
  14: flo_render::gl_renderer::renderer::GlRenderer::render
  15: std::thread::local::LocalKey<T>::with
  16: futures_executor::local_pool::block_on
  17: <O as gtk::auto::gl_area::GLAreaExt>::connect_render::render_trampoline
  18: ffi_call_unix64
  19: ffi_call
  20: g_cclosure_marshal_generic_va
  21: <unknown>
  22: g_signal_emit_valist
  23: g_signal_emit
  24: <unknown>
  25: <unknown>
  26: gtk_container_propagate_draw
  27: <unknown>
  28: <unknown>
  29: <unknown>
  30: gtk_container_propagate_draw
  31: <unknown>
  32: <unknown>
  33: <unknown>
  34: gtk_container_propagate_draw
  35: <unknown>
  36: <unknown>
  37: <unknown>
  38: <unknown>
  39: <unknown>
  40: <unknown>
  41: gtk_container_propagate_draw
  42: <unknown>
  43: <unknown>
  44: gtk_container_propagate_draw
  45: <unknown>
  46: <unknown>
  47: gtk_container_propagate_draw
  48: <unknown>
  49: <unknown>
  50: gtk_container_propagate_draw
  51: <unknown>
  52: <unknown>
  53: gtk_container_propagate_draw
  54: <unknown>
  55: <unknown>
  56: <unknown>
  57: gtk_container_propagate_draw
  58: <unknown>
  59: <unknown>
  60: <unknown>
  61: gtk_container_propagate_draw
  62: <unknown>
  63: <unknown>
  64: <unknown>
  65: <unknown>
  66: gtk_main_do_event
  67: <unknown>
  68: <unknown>
  69: <unknown>
  70: <unknown>
  71: g_closure_invoke
  72: <unknown>
  73: g_signal_emit_valist
  74: g_signal_emit
  75: <unknown>
  76: <unknown>
  77: <unknown>
  78: g_main_context_dispatch
  79: <unknown>
  80: g_main_loop_run
  81: gtk_main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Logicalshift** [comment]
Aha, oops, I added error handling while looking for a different issue and then got distracted before fixing the issues I found. This should be fixed now: problem was a bad call to `glUniformMatrix4fv` (with no effect other than generating an error).

**Comment by bjorn3** [comment]
Thanks, I can now actually open a file.
